name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheel
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Install package
        run: |
          pip install dist/*.whl

      - name: Smoke import
        run: |
          python - <<'PY'
          import importlib.metadata as md
          print('version', md.version('asciiquarium-redux'))
          import asciiquarium_redux
          print('import ok')
          PY
